# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07b7483249d0a753d3c7e7deb3bfa8864646784e20f789fe80022ced8e941f0cffb8de811795857760b1acf80934b35d783ad4cb7fc0b701ebf43231a9039600

test:
  secret_key_base: b1ea64d816dbe1554276381e909e814102288092bc00351cb692db7e9efd6826bcda7f5b865c4ef0809562ca9a307719a25a5a6e4591e524cc6caf249c38649f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
